"""Every persisted entity id (agent_id, thread_id, run_id, task_id,
message_id) is generated by the database itself (souk.db's souk_new_id
function and the DEFAULT clauses using it) — never precomputed in Python
and handed to Postgres as a value to store. The one deliberate exception,
A2A's caller-supplied task_id, is covered by test_api_a2a.py instead
(it's a real A2A call, not a repo-level concern).
"""

from __future__ import annotations

from souk import repo


async def test_register_agents_assigns_a_database_generated_agent_id(session, new_identity):
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    assert agent_ids["a"].startswith("agent_")


async def test_register_agents_reuses_the_same_agent_id_on_re_registration(session, new_identity):
    identity = new_identity()
    first = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    second = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    assert first["a"] == second["a"]


async def test_ensure_thread_assigns_a_database_generated_thread_id(session, new_identity):
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.ensure_thread(session, agent_ids["a"], None)
    assert thread_id.startswith("thread_")


async def test_create_run_assigns_a_database_generated_run_id_and_task_id(session, new_identity):
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.ensure_thread(session, agent_ids["a"], None)

    without_task = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})
    assert without_task["run_id"].startswith("run_")
    assert without_task["task_id"] is None

    with_task = await repo.create_run(
        session, thread_id, agent_ids["a"], "ag-ui", {}, assign_task_id=True
    )
    assert with_task["task_id"].startswith("task_")
    # A different run than the first — ids aren't reused across calls.
    assert with_task["run_id"] != without_task["run_id"]


async def test_append_thread_messages_discards_any_caller_supplied_id(session, new_identity):
    """A caller-supplied `id` is never trusted as this row's real
    identity — the database assigns its own, and the returned message
    reflects that, not whatever the caller sent.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.ensure_thread(session, agent_ids["a"], None)
    run = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})

    stored = await repo.append_thread_messages(
        session,
        thread_id,
        run["run_id"],
        [{"id": "whatever-the-caller-made-up", "role": "user", "content": "hi"}],
    )
    assert stored[0]["id"] != "whatever-the-caller-made-up"
    assert stored[0]["id"].startswith("msg_")

    # What's actually persisted matches what was returned, not the
    # caller's original id.
    persisted = await repo.get_thread_messages(session, thread_id)
    assert persisted[0]["id"] == stored[0]["id"]


async def test_append_thread_messages_never_deduplicates_by_content(session, new_identity):
    """Every call assigns a fresh id, so "sending the same message twice"
    (which shouldn't happen — thread_id already makes resending
    unnecessary, see souk-agent-sdk's README) produces two distinct rows,
    not one. There is no longer an id a caller can reuse to opt into
    dedup.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.ensure_thread(session, agent_ids["a"], None)
    run = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})

    same_content = [{"role": "user", "content": "hi"}]
    await repo.append_thread_messages(session, thread_id, run["run_id"], same_content)
    await repo.append_thread_messages(session, thread_id, run["run_id"], same_content)

    persisted = await repo.get_thread_messages(session, thread_id)
    assert len(persisted) == 2
    assert persisted[0]["id"] != persisted[1]["id"]
