"""Every persisted entity id (agent_id, thread_id, run_id, message_id) is
generated by the database itself (souk.db's souk_new_id function and the
DEFAULT clauses using it) — never precomputed in Python and handed to
Postgres as a value to store. There is no separate task_id concept — see
souk/db.py's module docstring; A2A's own caller-supplied `params.id` is
covered by test_api_a2a.py instead (it's accepted and ignored, a real
A2A-call concern, not a repo-level one).
"""

from __future__ import annotations

from souk import repo


async def test_register_agents_assigns_a_database_generated_agent_id(session, new_identity):
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    assert agent_ids["a"].startswith("agent_")


async def test_register_agents_reuses_the_same_agent_id_on_re_registration(session, new_identity):
    identity = new_identity()
    first = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    second = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    assert first["a"] == second["a"]


async def test_create_thread_assigns_a_database_generated_thread_id(session, new_identity):
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.create_thread(session, agent_ids["a"])
    assert thread_id.startswith("thread_")


async def test_ensure_thread_mints_a_fresh_thread_when_neither_id_is_given(session, new_identity):
    """The normal A2A first-contact case (no `contextId` at all) — see
    souk-no-forced-protocol-deviation: a caller was never required to
    call `POST /threads` first.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.ensure_thread(session, agent_ids["a"], None)
    assert thread_id.startswith("thread_")


async def test_ensure_thread_rejects_an_unknown_thread_id_by_default(session, new_identity):
    """A caller-*supplied* thread_id/contextId that doesn't exist is a
    real error (default create_if_missing=False) — it's claiming to
    continue something specific, unlike the no-id-at-all case above.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    try:
        await repo.ensure_thread(session, agent_ids["a"], "thread_made_up")
        assert False, "expected ThreadNotFound"
    except repo.ThreadNotFound:
        pass


async def test_ensure_thread_creates_under_an_unknown_id_when_told_to(session, new_identity):
    """AG-UI's case (create_if_missing=True): an unrecognized `threadId`
    mints a real, database-generated thread rather than 404ing — the
    caller's own string is discarded, not reused as the primary key.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.ensure_thread(
        session, agent_ids["a"], "thread_made_up", create_if_missing=True
    )
    assert thread_id.startswith("thread_")
    assert thread_id != "thread_made_up"


async def test_create_run_assigns_a_database_generated_run_id(session, new_identity):
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.create_thread(session, agent_ids["a"])

    first = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})
    assert first["run_id"].startswith("run_")

    second = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})
    # A different run than the first — ids aren't reused across calls.
    assert second["run_id"] != first["run_id"]


async def test_append_thread_messages_discards_any_caller_supplied_id(session, new_identity):
    """A caller-supplied `id` is never trusted as this row's real
    identity — the database assigns its own, and the returned message
    reflects that, not whatever the caller sent.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.create_thread(session, agent_ids["a"])
    run = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})

    stored = await repo.append_thread_messages(
        session,
        thread_id,
        run["run_id"],
        [{"id": "whatever-the-caller-made-up", "role": "user", "content": "hi"}],
    )
    assert stored[0]["id"] != "whatever-the-caller-made-up"
    assert stored[0]["id"].startswith("msg_")

    # What's actually persisted matches what was returned, not the
    # caller's original id.
    persisted = await repo.get_thread_messages(session, thread_id)
    assert persisted[0]["id"] == stored[0]["id"]


async def test_append_thread_messages_never_deduplicates_by_content(session, new_identity):
    """Every call assigns a fresh id, so "sending the same message twice"
    (which shouldn't happen — thread_id already makes resending
    unnecessary, see souk-agent-sdk's README) produces two distinct rows,
    not one. There is no longer an id a caller can reuse to opt into
    dedup.
    """
    identity = new_identity()
    agent_ids = await repo.register_agents(session, "sdk_1", identity.public_key, [{"name": "a"}])
    thread_id = await repo.create_thread(session, agent_ids["a"])
    run = await repo.create_run(session, thread_id, agent_ids["a"], "ag-ui", {})

    same_content = [{"role": "user", "content": "hi"}]
    await repo.append_thread_messages(session, thread_id, run["run_id"], same_content)
    await repo.append_thread_messages(session, thread_id, run["run_id"], same_content)

    persisted = await repo.get_thread_messages(session, thread_id)
    assert len(persisted) == 2
    assert persisted[0]["id"] != persisted[1]["id"]
