"""initial schema

Revision ID: 6f326dc19242
Revises:
Create Date: 2026-08-16

souk's baseline schema, built with dialect-neutral SQLAlchemy Core ops so it
renders correctly on both SQLite (souk's zero-config default) and Postgres —
see souk/schema.py, the single source of truth these ops mirror, for the
per-table/column reasoning.

This file is intentionally self-contained (it does not import souk.schema):
it is a frozen snapshot of the schema at this revision. Later schema changes
are new migrations, not edits to this file.

It replaces baseline b1e0d9c73a55, whose `thread_history` table held runs and
messages together under a `kind` column. They are now `runs` and
`thread_messages`, which is what lets `runs.run_id` be a primary key (it was
a partial unique index working around message rows sharing the id) and lets
`run_events.run_id` and `thread_messages.run_id` be real foreign keys. souk
has never been released, so the schema is rebaselined rather than migrated,
on the same reasoning b1e0d9c73a55 itself recorded.

Anyone holding a database created by the old baseline should recreate it —
its alembic_version names a revision that no longer exists.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f326dc19242'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Kept in sync with souk/schema.py's _JSON / _TS / _BIGSERIAL.
_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('agent_card', _JSON, nullable=False),
    sa.Column('metadata', _JSON, nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('public_key', 'name', name='uq_agents_public_key_name')
    )
    op.create_table('providers',
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('public_key'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('parent_thread_id', sa.String(), nullable=True),
    sa.Column('metadata', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['parent_thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index('idx_threads_parent', 'threads', ['parent_thread_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', _JSON, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("protocol IN ('ag-ui', 'a2a')", name='ck_runs_protocol'),
    sa.CheckConstraint("status IN ('queued', 'running', 'input-required', 'cancelling', 'completed', 'failed', 'cancelled')", name='ck_runs_status'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_runs_agent_status', 'runs', ['agent_id', 'status'], unique=False)
    op.create_index('idx_runs_thread', 'runs', ['thread_id', 'created_at'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_json', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_events_run', 'run_events', ['run_id', 'seq'], unique=False)
    op.create_table('thread_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('message_json', _JSON, nullable=False),
    sa.Column('metadata', _JSON, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'message_id', name='uq_thread_messages_thread_message')
    )
    op.create_index('idx_thread_messages_thread', 'thread_messages', ['thread_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_thread_messages_thread', table_name='thread_messages')
    op.drop_table('thread_messages')
    op.drop_index('idx_run_events_run', table_name='run_events')
    op.drop_table('run_events')
    op.drop_index('idx_runs_thread', table_name='runs')
    op.drop_index('idx_runs_agent_status', table_name='runs')
    op.drop_table('runs')
    op.drop_index('idx_threads_parent', table_name='threads')
    op.drop_table('threads')
    op.drop_table('providers')
    op.drop_table('agents')
    # ### end Alembic commands ###
