# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: souk.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'souk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsouk.proto\x12\x04souk\"r\n\x0bPollRequest\x12\x11\n\tagent_ids\x18\x01 \x03(\t\x12\x16\n\tmax_claim\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x19\n\x0cwait_seconds\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x0c\n\n_max_claimB\x0f\n\r_wait_seconds\"1\n\x0cPollResponse\x12!\n\x07pending\x18\x01 \x03(\x0b\x32\x10.souk.PendingRun\"D\n\nPendingRun\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x14\n\x0cjson_payload\x18\x03 \x01(\t\"y\n\x12\x41gentEventEnvelope\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x14\n\x0cjson_payload\x18\x03 \x01(\t\x12\x15\n\rend_of_stream\x18\x04 \x01(\x08\x12\x0e\n\x06\x63\x61ncel\x18\x06 \x01(\x08J\x04\x08\x05\x10\x06\x32\x90\x01\n\x10SoukAgentGateway\x12\x34\n\x0bPollForWork\x12\x11.souk.PollRequest\x1a\x12.souk.PollResponse\x12\x46\n\x0c\x41gentSession\x12\x18.souk.AgentEventEnvelope\x1a\x18.souk.AgentEventEnvelope(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'souk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLLREQUEST']._serialized_start=20
  _globals['_POLLREQUEST']._serialized_end=134
  _globals['_POLLRESPONSE']._serialized_start=136
  _globals['_POLLRESPONSE']._serialized_end=185
  _globals['_PENDINGRUN']._serialized_start=187
  _globals['_PENDINGRUN']._serialized_end=255
  _globals['_AGENTEVENTENVELOPE']._serialized_start=257
  _globals['_AGENTEVENTENVELOPE']._serialized_end=378
  _globals['_SOUKAGENTGATEWAY']._serialized_start=381
  _globals['_SOUKAGENTGATEWAY']._serialized_end=525
# @@protoc_insertion_point(module_scope)
