# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import souk_pb2 as souk__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in souk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SoukAgentGatewayStub:
    """gRPC contract between souk (server) and souk-agent-sdk (agent-side client).

    Envelopes carry raw AG-UI JSON rather than a fully-typed proto per AG-UI
    event: AG-UI already defines its own JSON event schemas and is still
    evolving (draft event categories), so re-typing every event here would
    mean chasing upstream churn for no real gain at this stage.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PollForWork = channel.unary_unary(
                '/souk.SoukAgentGateway/PollForWork',
                request_serializer=souk__pb2.PollRequest.SerializeToString,
                response_deserializer=souk__pb2.PollResponse.FromString,
                _registered_method=True)
        self.AgentSession = channel.stream_stream(
                '/souk.SoukAgentGateway/AgentSession',
                request_serializer=souk__pb2.AgentEventEnvelope.SerializeToString,
                response_deserializer=souk__pb2.AgentEventEnvelope.FromString,
                _registered_method=True)


class SoukAgentGatewayServicer:
    """gRPC contract between souk (server) and souk-agent-sdk (agent-side client).

    Envelopes carry raw AG-UI JSON rather than a fully-typed proto per AG-UI
    event: AG-UI already defines its own JSON event schemas and is still
    evolving (draft event categories), so re-typing every event here would
    mean chasing upstream churn for no real gain at this stage.
    """

    def PollForWork(self, request, context):
        """Called repeatedly by a provider's worker loop to claim work queued for
        its registered agents. Claiming *is* the hand-over: each pending run
        comes back with its RunAgentInput, so a worker leaves this call able to
        start running immediately. There is no follow-up exchange in which souk
        delivers the input, and therefore no window in which a run has been
        claimed but its worker is still waiting to be told what to do.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentSession(self, request_iterator, context):
        """One persistent, multiplexed, bidirectional stream shared by every run
        an SDK client currently has in flight. The reference SDK
        (souk-agent-sdk) opens this only once PollForWork has actually handed
        it work, and keeps it open only for as long as it keeps finding more
        — an idle client holds no AgentSession stream at all, just a
        periodic PollForWork call (see souk_agent_sdk.client for the exact
        lifecycle). Every run is claimed, delivered, and drained through
        whichever single connection is currently open — disambiguated by
        run_id on each envelope — rather than opening a new stream per run.

        This stream carries a worker's *output*. The run itself was already
        claimed, with its input, over PollForWork — so per run_id the exchange
        is only:
        1. sdk->souk: zero or more envelopes, each carrying one AG-UI event
        JSON for that run_id.
        2. sdk->souk: a final envelope for that run_id with end_of_stream
        true. Nothing comes back for that run_id afterwards — souk owns
        durability from the moment it has the events, and an agent has
        no recovery action available if that fails (it has already
        produced and discarded them), so there is deliberately no
        completion acknowledgement here. Whether a run persisted is a
        question its *caller* asks, via the run's own status.
        souk sends exactly one kind of frame the other way: `cancel` (below),
        asking a run to stop. (An earlier version of this contract opened with
        a claim envelope from the SDK and a RunAgentInput envelope back from
        souk. Both are gone: claiming carries the input now.)

        A run is addressed by run_id, not by connection — souk checks each
        frame against the identity that claimed that run rather than against
        the stream it arrived on. A worker that loses this stream mid-run may
        therefore reconnect and report the rest, including its end_of_stream,
        over the new one.
        Multiple run_ids can be in flight concurrently on the same stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoukAgentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PollForWork': grpc.unary_unary_rpc_method_handler(
                    servicer.PollForWork,
                    request_deserializer=souk__pb2.PollRequest.FromString,
                    response_serializer=souk__pb2.PollResponse.SerializeToString,
            ),
            'AgentSession': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentSession,
                    request_deserializer=souk__pb2.AgentEventEnvelope.FromString,
                    response_serializer=souk__pb2.AgentEventEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'souk.SoukAgentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('souk.SoukAgentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SoukAgentGateway:
    """gRPC contract between souk (server) and souk-agent-sdk (agent-side client).

    Envelopes carry raw AG-UI JSON rather than a fully-typed proto per AG-UI
    event: AG-UI already defines its own JSON event schemas and is still
    evolving (draft event categories), so re-typing every event here would
    mean chasing upstream churn for no real gain at this stage.
    """

    @staticmethod
    def PollForWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/souk.SoukAgentGateway/PollForWork',
            souk__pb2.PollRequest.SerializeToString,
            souk__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/souk.SoukAgentGateway/AgentSession',
            souk__pb2.AgentEventEnvelope.SerializeToString,
            souk__pb2.AgentEventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
