"""Souk-assigned ids: `<category>_<hex>`, no dashes.

Every souk id — both the ones backing a persisted entity (agents,
threads, runs, messages) and the ones that never become a row — is minted
here, in Python. This used to be split: persisted-entity ids were
generated by a Postgres-side `souk_new_id()` SQL function (pgcrypto's
`gen_random_bytes`) wired up as column DEFAULTs, and this module only
covered ids with nowhere to attach a column default to. That database
function only existed on Postgres; folding all id generation back into the
application layer is what lets the schema and queries stay dialect-neutral
so the same code runs on SQLite and Postgres alike (see souk/repo.py,
which now passes an explicit `new_id(...)` on insert instead of relying on
a DB default).

The wire format is unchanged from the old `souk_new_id`: a category prefix
plus 12 cryptographically-random bytes rendered as 24 lowercase hex chars,
so ids minted before and after this change are indistinguishable.

Callers that never touch a database row still use this too: a
provider-generated messageId gets remapped in souk.agui.rewrite_message_ids
(an assistant reply is relayed live, never stored as a thread_history row),
and souk.api_llm_bridge's in-memory KYOK request tracking.
"""

import secrets


def new_id(category: str) -> str:
    return f"{category}_{secrets.token_hex(12)}"
