"""Souk-assigned ids for things that never become a database row:
`<category>_<hex>`, no dashes — same shape as `souk_new_id()` (souk/db.py),
just generated in Python instead of by Postgres.

Every id backing an actual persisted entity (agents, threads, runs,
messages) is generated by the database itself now (see souk/db.py's
souk_new_id function and the DEFAULT clauses using it) — this module is
only for the couple of ids that have nowhere to live in a row to attach a
column default to: a provider-generated messageId gets remapped to one of
these in souk.agui.rewrite_message_ids (an assistant reply is relayed
live, never stored as a thread_history row), and souk.api_llm_bridge's
in-memory KYOK request tracking (never touches Postgres at all).
"""

import secrets


def new_id(category: str) -> str:
    return f"{category}_{secrets.token_hex(12)}"
