"""souk's database schema, defined once as SQLAlchemy Core table metadata.

This is the single source of truth for the schema. It replaces the old
hand-written raw-SQL DDL blob (a Postgres-only script full of JSONB,
TIMESTAMPTZ, BIGSERIAL and a pgcrypto-backed `souk_new_id()` function):
because the tables are declared with dialect-neutral SQLAlchemy types here,
the same definition renders correct DDL on both SQLite (souk's zero-config
default) and Postgres (see souk/core.py). Two things follow from that:

- souk/repo.py queries these tables through the Core expression language,
  so results come back as the same Python types (dict for JSON, datetime
  for timestamps) on either backend.
- souk/alembic/env.py points `target_metadata` here, and the initial
  migration builds these tables, so `alembic upgrade head` produces the
  schema on either backend from this one definition.

Entity ids (thread_id, run_id, message_id) are NOT generated by
the database anymore — repo.py mints them in Python via souk.ids.new_id and
passes them explicitly on insert (the old Postgres-side `souk_new_id`
DEFAULTs had no SQLite equivalent). Timestamps default to UTC-aware `now()`
in Python (`_utcnow`) rather than a SQL `DEFAULT now()`, so a single source
formats them consistently across dialects.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    BigInteger,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# JSONB on Postgres (indexable, the historical column type), plain JSON on
# everything else (SQLite stores it as TEXT and validates via JSON1). souk
# reads/writes these as Python dicts either way — merges are done in Python
# (repo.py), so no dialect-specific json operator is needed.
_JSON = JSON().with_variant(JSONB(), "postgresql")

# A tz-aware UTC timestamp. On Postgres this is TIMESTAMPTZ; on SQLite it is
# stored as an ISO string. repo.py always writes UTC (`_utcnow`), so values
# round-trip as UTC on both (see repo.is_agent_online, which normalizes).
_TS = DateTime(timezone=True)

# A big autoincrementing surrogate key. `.with_variant(Integer, "sqlite")`
# is required: SQLite only treats a column typed exactly `INTEGER PRIMARY
# KEY` as an alias for the auto-incrementing rowid — a `BIGINT PRIMARY KEY`
# would not autoincrement. On Postgres this stays BIGINT (identity).
_BIGSERIAL = BigInteger().with_variant(Integer(), "sqlite")


# One row per provider identity: every public_key that has registered,
# whether or not it chose a display name. It used to hold only the ones that
# passed a `provider_name`, which made it a table of labels rather than of
# identities — `fingerprint` needs the latter, since resolving a short
# address has to be able to miss for a key that exists but never named
# itself.
#
# Deliberately not folded into `agents`: both columns are properties of the
# key, set once per key rather than once per agent, and a display name
# shouldn't get wiped out because one registration batch didn't pass one
# (see repo.set_provider_name).
providers = Table(
    "providers",
    metadata,
    Column("public_key", String, primary_key=True),
    # The short form of public_key (souk.identity.provider_fingerprint) —
    # derived, so it can never drift from the key it belongs to, and UNIQUE
    # so a second key hashing to the same prefix is refused by the database
    # at registration rather than by a check that could race.
    Column("fingerprint", String, nullable=False, unique=True),
    # NULL means "this identity never said" — distinct from a name set and
    # later cleared, which souk does not offer.
    Column("display_name", String, nullable=True),
    Column("updated_at", _TS, nullable=False, default=_utcnow),
)


# An agent is `(provider_key, name)` and has no other identity — that pair is
# the primary key, and every reference to an agent anywhere is those two
# columns.
#
# There used to be an `agent_id` here, minted by souk, and the pair was a
# UNIQUE constraint beside it. It carried no information: repo.register_agents
# looked the id up by this pair and reused whatever it found, so the pair was
# the input and the id the output. What it did carry was a cost — a provider
# had to hold identifiers only souk could mint and echo them back on every
# call, so replacing the database made a running provider's whole vocabulary
# meaningless with no way for it to rebuild it (issue #37), and souk's own
# in-process worker could not recover even after re-registering, because fresh
# ids were minted and it kept serving the ones it was attached with.
#
# `provider_key` rather than `public_key`
# because an agent has no key: the key is its provider's, and this column has
# always meant that (its old comment said so).
agents = Table(
    "agents",
    metadata,
    # The provider's Ed25519 public key (hex) — see souk/identity.py. This
    # foreign key is new: the relationship was real all along and held
    # together only by repo.ensure_provider being called first, which is a
    # convention rather than a guarantee.
    Column("provider_key", String, ForeignKey("providers.public_key"), primary_key=True),
    # A free, human-facing label — and half of the identity. Not exclusive
    # across providers: two identities may both offer `translator`, which is
    # why the pair rather than the name is the key. Changing a name is not
    # supported and never was: it produces a different agent, which is the
    # reason a surrogate key bought nothing here.
    Column("name", String, primary_key=True),
    Column("agent_card", _JSON, nullable=False),
    # Free-form, souk-internal extension data — distinct from agent_card
    # (which is protocol-facing: served verbatim as the A2A Agent Card).
    # Not interpreted by souk itself.
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("joined_at", _TS, nullable=False, default=_utcnow),
    Column("last_seen_at", _TS, nullable=False, default=_utcnow),
)


# One row per LLM provider offering: the party that answers KYOK
# completions (see souk/kyok.py), shaped exactly like `agents` and for
# the same reasons. An offering is `(provider_key, name)` and has no
# other identity — names are deliberately NOT exclusive across
# identities: two providers both offering `gpt4` is normal, so a bare
# name cannot be an address and no one gets first-come ownership of a
# word. The caller binds a run with the pair
# (metadata.kyok.llmProvider = {providerKey, name}).
#
# The identity itself lives in `providers`, same as for agents — one key
# may sit in both rosters, and "identity is identity" holds in the
# database, not just in prose.
llm_providers = Table(
    "llm_providers",
    metadata,
    Column("provider_key", String, ForeignKey("providers.public_key"), primary_key=True),
    Column("name", String, primary_key=True),
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("joined_at", _TS, nullable=False, default=_utcnow),
    Column("last_seen_at", _TS, nullable=False, default=_utcnow),
)


threads = Table(
    "threads",
    metadata,
    Column("thread_id", String, primary_key=True),
    # Which agent this thread is with: the pair, because that is what an
    # agent is (see the agents table).
    Column("provider_key", String, nullable=False),
    Column("agent_name", String, nullable=False),
    # Set when this thread was spawned by an A2A call from within another
    # thread's run (e.g. a main agent delegating to a sub-agent) — pure
    # lineage, so "what conversation led to this one" is queryable. NULL for
    # a thread started directly by a top-level caller.
    Column("parent_thread_id", String, ForeignKey("threads.thread_id"), nullable=True),
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    Column("last_activity_at", _TS, nullable=False, default=_utcnow),
    ForeignKeyConstraint(
        ["provider_key", "agent_name"], ["agents.provider_key", "agents.name"],
        name="fk_threads_agent",
    ),
    Index("idx_threads_parent", "parent_thread_id"),
)


# One run: an AG-UI run and an A2A task are the same thing under two
# protocols, and A2A's `Task.id` *is* this `run_id` (see protocols.a2a) — so
# the identifier every caller addresses is this table's primary key.
#
# It could not be, until this table existed. Runs and messages used to share
# one `thread_history` table with a `kind` column saying which a row was, and
# the messages a run produced carry that run's id too — so `run_id` was not
# unique in the table and had to be addressed through a partial unique index
# (`WHERE kind = 'run_status'`) standing in for a key.
#
# The merge existed so the two kinds could be interleaved by one
# autoincrementing `id` and read back in true chronological order. Nothing
# ever read that interleaving: every query in repo.py filtered by `kind`.
# What it charged for the ordering nobody used was a NULL half on every row
# (a message row carried seven NULL run columns), a `kind` predicate that
# silently matches the wrong rows when forgotten — repo.get_run shipped
# exactly that bug, returning message columns as facts about a run — and the
# primary key above.
runs = Table(
    "runs",
    metadata,
    # Minted in Python by repo.create_run (souk.ids.new_id('run')).
    Column("run_id", String, primary_key=True),
    Column("thread_id", String, ForeignKey("threads.thread_id"), nullable=False),
    Column("provider_key", String, nullable=False),
    Column("agent_name", String, nullable=False),
    Column("protocol", String, nullable=False),
    # 'input-required': the run is paused/resumable instead of finished — a
    # provider signaled this via AG-UI's own native interrupt outcome (see
    # souk/pause.py) rather than completing normally. Not terminal like the
    # other non-active statuses: resuming reopens this *same* row under its
    # existing run_id for another round (see repo.reopen_run) so a run's
    # identity stays stable across pause/resume rounds.
    #
    # 'cancelling': souk has asked the provider to stop and it still has the
    # run. Non-terminal, and deliberately distinct from 'cancelled' — souk
    # can ask, it cannot compel, so whether the run was really cancelled is
    # only knowable once the agent's stream ends. A provider that ignores
    # the request and finishes normally has completed, and recording
    # 'cancelled' up front would assert something souk never verified (see
    # handlers._handle_finish for how the outcome is decided). Counts as
    # active, and as still-running for the stall sweep, so a provider that
    # never answers is eventually reaped instead of hanging here.
    Column("status", String, nullable=False),
    Column("input_json", _JSON, nullable=False),
    Column("started_at", _TS, nullable=True),
    Column("completed_at", _TS, nullable=True),
    # Bumped on every status change and every event relayed for this run
    # (see repo.mark_run_status / repo.touch_run_activity) — how souk tells
    # "provider claimed this and is making progress" apart from "claimed and
    # then went silent" (see the periodic stall sweep in souk.health).
    Column("last_activity_at", _TS, nullable=True),
    # An A2A Task's own `metadata` field, plus souk's own annotations
    # (failureReason, pause payloads).
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    # NOT NULL on the agent columns, protocol, status and input_json is part of what the
    # split buys: every one of them is set by repo.create_run and always has
    # been, and they were nullable only because message rows shared the table
    # and had nothing to put there.
    CheckConstraint("protocol IN ('ag-ui', 'a2a')", name="ck_runs_protocol"),
    # 'resumed' is gone from this list. It was accepted but never written,
    # kept only so the old CHECK would not reject rows predating the current
    # pause/resume model — and this is a new table, so there are none.
    CheckConstraint(
        "status IN ('queued', 'running', 'input-required', 'cancelling', 'completed', 'failed', 'cancelled')",
        name="ck_runs_status",
    ),
    ForeignKeyConstraint(
        ["provider_key", "agent_name"], ["agents.provider_key", "agents.name"],
        name="fk_runs_agent",
    ),
    Index("idx_runs_thread", "thread_id", "created_at"),
    # What claiming reads: queued runs for the agents one provider serves.
    Index("idx_runs_agent_status", "provider_key", "agent_name", "status"),
)


# The thread's conversation: one row per AG-UI Message, in `id` order.
#
# `run_id` is a real foreign key here, which it could not be while runs lived
# in this same table — a message names the run that introduced it, and now
# the database holds that rather than trusting every caller to.
thread_messages = Table(
    "thread_messages",
    metadata,
    Column("id", _BIGSERIAL, primary_key=True, autoincrement=True),
    Column("thread_id", String, ForeignKey("threads.thread_id"), nullable=False),
    Column("run_id", String, ForeignKey("runs.run_id"), nullable=False),
    # Minted in Python by repo.append_thread_messages (souk.ids.new_id('msg'));
    # a caller-supplied id is never trusted as this row's real identity.
    Column("message_id", String, nullable=False),
    Column("message_json", _JSON, nullable=False),
    # Whatever metadata the AG-UI Message carried.
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    UniqueConstraint("thread_id", "message_id", name="uq_thread_messages_thread_message"),
    Index("idx_thread_messages_thread", "thread_id", "id"),
)


# The raw AG-UI event stream for a run (tool calls, state deltas, …) — a
# different granularity from `thread_messages`, which holds the conversation
# those events reduce to (see souk/agui_reduce.py).
#
# `run_id` is a foreign key. Its comment used to say the integrity was
# "enforced at the application layer instead", because runs shared a table
# with messages and the column it needed to reference was not unique there.
# Nothing enforced it: wiping souk's tables mid-run and then reporting an
# event wrote two rows here belonging to a run that did not exist, and the
# run finished leaving no trace. The database refuses that now, which also
# means a souk whose database was replaced underneath it finds out on its
# next write instead of never.
run_events = Table(
    "run_events",
    metadata,
    Column("id", _BIGSERIAL, primary_key=True, autoincrement=True),
    Column("run_id", String, ForeignKey("runs.run_id"), nullable=False),
    Column("seq", Integer, nullable=False),
    Column("event_json", _JSON, nullable=False),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    Index("idx_run_events_run", "run_id", "seq"),
)
