"""souk's database schema, defined once as SQLAlchemy Core table metadata.

This is the single source of truth for the schema. It replaces the old
hand-written raw-SQL DDL blob (a Postgres-only script full of JSONB,
TIMESTAMPTZ, BIGSERIAL and a pgcrypto-backed `souk_new_id()` function):
because the tables are declared with dialect-neutral SQLAlchemy types here,
the same definition renders correct DDL on both SQLite (souk's zero-config
default) and Postgres (see souk/db.py). Two things follow from that:

- souk/repo.py queries these tables through the Core expression language,
  so results come back as the same Python types (dict for JSON, datetime
  for timestamps) on either backend.
- souk/alembic/env.py points `target_metadata` here, and the initial
  migration builds these tables, so `alembic upgrade head` produces the
  schema on either backend from this one definition.

Entity ids (agent_id, thread_id, run_id, message_id) are NOT generated by
the database anymore — repo.py mints them in Python via souk.ids.new_id and
passes them explicitly on insert (the old Postgres-side `souk_new_id`
DEFAULTs had no SQLite equivalent). Timestamps default to UTC-aware `now()`
in Python (`_utcnow`) rather than a SQL `DEFAULT now()`, so a single source
formats them consistently across dialects.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    BigInteger,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# JSONB on Postgres (indexable, the historical column type), plain JSON on
# everything else (SQLite stores it as TEXT and validates via JSON1). souk
# reads/writes these as Python dicts either way — merges are done in Python
# (repo.py), so no dialect-specific json operator is needed.
_JSON = JSON().with_variant(JSONB(), "postgresql")

# A tz-aware UTC timestamp. On Postgres this is TIMESTAMPTZ; on SQLite it is
# stored as an ISO string. repo.py always writes UTC (`_utcnow`), so values
# round-trip as UTC on both (see repo.is_agent_online, which normalizes).
_TS = DateTime(timezone=True)

# A big autoincrementing surrogate key. `.with_variant(Integer, "sqlite")`
# is required: SQLite only treats a column typed exactly `INTEGER PRIMARY
# KEY` as an alias for the auto-incrementing rowid — a `BIGINT PRIMARY KEY`
# would not autoincrement. On Postgres this stays BIGINT (identity).
_BIGSERIAL = BigInteger().with_variant(Integer(), "sqlite")


# A "provider" isn't a first-class registration concept the way an agent
# is — it's just whoever holds a given public_key, identified purely by
# that key (see agents.public_key). This table exists only to attach an
# optional, non-unique display label to that key for humans browsing the
# directory (souk-directory groups agents by public_key into
# "storefronts"). Deliberately not folded into `agents`: a provider's name
# is set once per key, not once per agent, and shouldn't get wiped out just
# because one particular registration batch didn't happen to pass it (see
# repo.upsert_provider_name).
providers = Table(
    "providers",
    metadata,
    Column("public_key", String, primary_key=True),
    Column("display_name", String, nullable=False),
    Column("updated_at", _TS, nullable=False, default=_utcnow),
)


agents = Table(
    "agents",
    metadata,
    # Minted in Python (souk.ids.new_id('agent') — see repo.register_agents,
    # which reuses an existing id for an already-registered (public_key,
    # name) pair and mints a fresh one otherwise) — the real
    # routing/ownership key. `name` below is deliberately NOT this: it's a
    # free, non-unique, human-facing label (multiple identities may register
    # the same name; see the UNIQUE(public_key, name) constraint instead).
    Column("agent_id", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("sdk_client_id", String, nullable=False),
    # Ed25519 public key (hex) that owns this agent_id — see
    # souk/identity.py. Set once at first registration of this (public_key,
    # name) pair, never changed by a later one. Whoever holds the matching
    # private key owns this agent_id; `name` itself is not exclusive, so a
    # different public_key may freely reuse the same name.
    Column("public_key", String, nullable=False),
    Column("agent_card", _JSON, nullable=False),
    # Free-form, souk-internal extension data — distinct from agent_card
    # (which is protocol-facing: served verbatim as the A2A Agent Card).
    # Not interpreted by souk itself.
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("joined_at", _TS, nullable=False, default=_utcnow),
    Column("last_seen_at", _TS, nullable=False, default=_utcnow),
    # Soft-delist marker, NULL = listed. Set when a registration batch from
    # this public_key omits a previously-registered agent_id (see
    # repo.register_agents), or cleared again if it reappears in a later
    # batch. Never hard-deleted — threads/thread_history still reference
    # agent_id, and the audit trail should survive de-listing.
    Column("delisted_at", _TS, nullable=True),
    UniqueConstraint("public_key", "name", name="uq_agents_public_key_name"),
)


threads = Table(
    "threads",
    metadata,
    Column("thread_id", String, primary_key=True),
    Column("agent_id", String, ForeignKey("agents.agent_id"), nullable=False),
    # Set when this thread was spawned by an A2A call from within another
    # thread's run (e.g. a main agent delegating to a sub-agent) — pure
    # lineage, so "what conversation led to this one" is queryable. NULL for
    # a thread started directly by a top-level caller.
    Column("parent_thread_id", String, ForeignKey("threads.thread_id"), nullable=True),
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    Column("last_activity_at", _TS, nullable=False, default=_utcnow),
    Index("idx_threads_parent", "parent_thread_id"),
)


# A2A's task state and AG-UI's conversation history are two views onto the
# same underlying conversation (a souk "thread" == an A2A session), so they
# live in one table rather than split across a separate task/run table and a
# separate message table. Each row is either:
#   kind='message'    — one AG-UI Message, part of the thread's history
#   kind='run_status' — the state of one run/A2A task within the thread
# ordered together by `id` so the two interleave in true chronological
# order. (run_id is NOT this table's primary key: a run_status row is one
# among many rows sharing that run_id, since the messages it introduced
# carry the same run_id.)
thread_history = Table(
    "thread_history",
    metadata,
    Column("id", _BIGSERIAL, primary_key=True, autoincrement=True),
    Column("thread_id", String, ForeignKey("threads.thread_id"), nullable=False),
    # For a fresh 'run_status' row repo.create_run mints this in Python
    # (souk.ids.new_id('run')); a 'message' row belonging to an existing run
    # passes that run's id explicitly.
    Column("run_id", String, nullable=False),
    Column("kind", String, nullable=False),
    # kind = 'message' — minted in Python by repo.append_thread_messages
    # (souk.ids.new_id('msg')); a caller-supplied id is never trusted. A
    # 'run_status' row sets this explicitly NULL.
    Column("message_id", String, nullable=True),
    Column("message_json", _JSON, nullable=True),
    # kind = 'run_status'
    Column("agent_id", String, nullable=True),
    Column("protocol", String, nullable=True),
    # 'input-required': the run is paused/resumable instead of finished — a
    # provider signaled this via AG-UI's own native interrupt outcome (see
    # souk/pause.py) rather than completing normally. Not terminal like the
    # other non-active statuses: resuming reopens this *same* row under its
    # existing run_id for another round (see repo.reopen_run) so a run's
    # identity stays stable across pause/resume rounds. 'resumed' is
    # accepted but no longer written — kept so this CHECK doesn't reject
    # pre-existing rows from before pause/resume was tracked this way.
    Column("status", String, nullable=True),
    Column("input_json", _JSON, nullable=True),
    Column("started_at", _TS, nullable=True),
    Column("completed_at", _TS, nullable=True),
    # Bumped on every status change and every event relayed for this run
    # (see repo.mark_run_status / repo.touch_run_activity) — how souk tells
    # "provider claimed this and is making progress" apart from "claimed and
    # then went silent" (see the periodic stall sweep in souk.health).
    Column("last_activity_at", _TS, nullable=True),
    # Free-form extension data, meaning depends on `kind`: for a message
    # row, whatever metadata the AG-UI Message carried; for a run_status
    # row, an A2A Task/Message's own `metadata` field.
    Column("metadata", _JSON, nullable=False, default=dict),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    CheckConstraint("kind IN ('message', 'run_status')", name="ck_thread_history_kind"),
    CheckConstraint("protocol IN ('ag-ui', 'a2a')", name="ck_thread_history_protocol"),
    CheckConstraint(
        "status IN ('queued', 'running', 'input-required', 'resumed', 'completed', 'failed', 'cancelled')",
        name="ck_thread_history_status",
    ),
    UniqueConstraint("thread_id", "message_id", name="uq_thread_history_thread_message"),
    Index("idx_thread_history_thread", "thread_id", "id"),
)

# A2A's Task.id is just a run_id (see api_a2a._start_run) — no separate
# task_id concept, so this partial unique index is what both souk's own
# dispatch and A2A's tasks/get / tasks/cancel lookups rely on. Partial
# (WHERE kind = 'run_status') because the same run_id also appears on the
# 'message' rows that run introduced. Both SQLite and Postgres support
# partial indexes; the predicate is identical, just declared per-dialect.
Index(
    "idx_thread_history_run_status_run_id",
    thread_history.c.run_id,
    unique=True,
    sqlite_where=text("kind = 'run_status'"),
    postgresql_where=text("kind = 'run_status'"),
)


# Finer-grained than thread_history's per-run status/history: the raw AG-UI
# event stream for a run (tool calls, state deltas, ...), kept separately
# since it's a different granularity than "conversation history". Not FK'd
# to thread_history.run_id since that column isn't uniquely constrained
# across the whole table (only among run_status rows) — enforced at the
# application layer instead.
run_events = Table(
    "run_events",
    metadata,
    Column("id", _BIGSERIAL, primary_key=True, autoincrement=True),
    Column("run_id", String, nullable=False),
    Column("seq", Integer, nullable=False),
    Column("event_json", _JSON, nullable=False),
    Column("created_at", _TS, nullable=False, default=_utcnow),
    Index("idx_run_events_run", "run_id", "seq"),
)
